# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2451a86a7d84a3d266dc65ae84d23e5ed299f5a90092817affc3dd7d604e911fb8fd5a06dae09a96c2e5ff0a72e89ec34863ac1a04ae0c512c21521ae58f73

test:
  secret_key_base: ea4b7c67e1bdcc76307f91966a993b15d82c03ec0f8eb0cdd72ed59819eee650a13207c42c211397d505963c343cdb6fcd104f2edf50088cd25f15efb1d88108

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
